# coding: utf-8

# flake8: noqa
"""
    Sentim's Emotion APIs

    An emotion recognition api that tells you the emotion of text, and not just the connotation.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: help@sentimllc.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from sentim.models.batch_emotion_response import BatchEmotionResponse
from sentim.models.batch_text import BatchText
from sentim.models.conversation import Conversation
from sentim.models.conversation_response import ConversationResponse
from sentim.models.conversation_score import ConversationScore
from sentim.models.emotion_response import EmotionResponse
from sentim.models.emotion_score import EmotionScore
from sentim.models.error_item import ErrorItem
from sentim.models.result_item import ResultItem
from sentim.models.text import Text
