# coding: utf-8

"""
    Sentim's Emotion APIs

    An emotion recognition api that tells you the emotion of text, and not just the connotation.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: help@sentimllc.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ConversationResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'error_list': 'list[ErrorItem]',
        'result_list': 'list[ConversationScore]'
    }

    attribute_map = {
        'error_list': 'ErrorList',
        'result_list': 'ResultList'
    }

    def __init__(self, error_list=None, result_list=None):  # noqa: E501
        """ConversationResponse - a model defined in OpenAPI"""  # noqa: E501

        self._error_list = None
        self._result_list = None
        self.discriminator = None

        if error_list is not None:
            self.error_list = error_list
        if result_list is not None:
            self.result_list = result_list

    @property
    def error_list(self):
        """Gets the error_list of this ConversationResponse.  # noqa: E501

        The list of errors that occured during the execution of this method.  # noqa: E501

        :return: The error_list of this ConversationResponse.  # noqa: E501
        :rtype: list[ErrorItem]
        """
        return self._error_list

    @error_list.setter
    def error_list(self, error_list):
        """Sets the error_list of this ConversationResponse.

        The list of errors that occured during the execution of this method.  # noqa: E501

        :param error_list: The error_list of this ConversationResponse.  # noqa: E501
        :type: list[ErrorItem]
        """

        self._error_list = error_list

    @property
    def result_list(self):
        """Gets the result_list of this ConversationResponse.  # noqa: E501

        The list of index and effective score for every chatbot message.  # noqa: E501

        :return: The result_list of this ConversationResponse.  # noqa: E501
        :rtype: list[ConversationScore]
        """
        return self._result_list

    @result_list.setter
    def result_list(self, result_list):
        """Sets the result_list of this ConversationResponse.

        The list of index and effective score for every chatbot message.  # noqa: E501

        :param result_list: The result_list of this ConversationResponse.  # noqa: E501
        :type: list[ConversationScore]
        """

        self._result_list = result_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConversationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
