# coding: utf-8

"""
    Sentim's Emotion APIs

    An emotion recognition api that tells you the emotion of text, and not just the connotation.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: help@sentimllc.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ErrorItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'index': 'int',
        'error_message': 'str',
        'error_code': 'int'
    }

    attribute_map = {
        'index': 'Index',
        'error_message': 'ErrorMessage',
        'error_code': 'ErrorCode'
    }

    def __init__(self, index=None, error_message=None, error_code=None):  # noqa: E501
        """ErrorItem - a model defined in OpenAPI"""  # noqa: E501

        self._index = None
        self._error_message = None
        self._error_code = None
        self.discriminator = None

        if index is not None:
            self.index = index
        if error_message is not None:
            self.error_message = error_message
        if error_code is not None:
            self.error_code = error_code

    @property
    def index(self):
        """Gets the index of this ErrorItem.  # noqa: E501

        The index of the conversation or list that the error occurred.  # noqa: E501

        :return: The index of this ErrorItem.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this ErrorItem.

        The index of the conversation or list that the error occurred.  # noqa: E501

        :param index: The index of this ErrorItem.  # noqa: E501
        :type: int
        """

        self._index = index

    @property
    def error_message(self):
        """Gets the error_message of this ErrorItem.  # noqa: E501

        The message describing what went wrong.  # noqa: E501

        :return: The error_message of this ErrorItem.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this ErrorItem.

        The message describing what went wrong.  # noqa: E501

        :param error_message: The error_message of this ErrorItem.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def error_code(self):
        """Gets the error_code of this ErrorItem.  # noqa: E501

        The error code of the message. Usually one of https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.  # noqa: E501

        :return: The error_code of this ErrorItem.  # noqa: E501
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this ErrorItem.

        The error code of the message. Usually one of https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.  # noqa: E501

        :param error_code: The error_code of this ErrorItem.  # noqa: E501
        :type: int
        """

        self._error_code = error_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
